resugar/resugar

- src/plugins/modules.commonjs.js
- test/form/modules.commonjs/rewrites-assigning-a-complex-object-as-export-default/_expected/main.js
- test/form/modules.commonjs/rewrites-assigning-a-complex-object-as-export-default/_expected/metadata.json
- test/form/modules.commonjs/rewrites-assigning-a-complex-object-as-export-default/main.js
This is a quick fix to fix a bunch of crashes I've seen in decaffeinate.
Currently the code assumes that exported object keys and values are identifiers,
and crashes if they're not. With this change, the code instead falls back to the
normal `export default` case with the object.
@eventualbuddha , I wrote this before I saw you had assigned #92 to yourself, I hope I'm not stepping on your toes. I saw you have more interesting plans in #90, but fixing the crash as a stopgap would be nice.
> fix: don't crash when the export object contains non-identifiers

- src/esnext.js
- src/module.js
- test/form/modules.commonjs/works-with-object-destructuring-for-named-exports/_expected/ast.json
- test/form/modules.commonjs/works-with-object-destructuring-for-named-exports/_expected/main.js
- test/form/modules.commonjs/works-with-object-destructuring-for-named-exports/_expected/metadata.json
- test/form/modules.commonjs/works-with-object-destructuring-for-named-exports/main.js
BREAKING CHANGE: Removes 'map' property from rendered modules because it's too annoying to maintain the source map chain.
This fixes whole classes of bugs caused by interactions between plugins.
Closes #101
See also https://github.com/decaffeinate/decaffeinate/issues/335
> fix: reinitialize modules between plugins

- src/esnext.js
This is the esnext side of a change to make the decaffeinate repl more useful
for figuring out intermediate esnext errors. When esnext throws a parse error,
the position information in the exception refers to the intermediate source
code, but decaffeinate interprets it as a position in the original code sent to
esnext, which leads to some confusing-looking errors, such as in this bug
report:
https://github.com/decaffeinate/decaffeinate/issues/500
To avoid this problem, we can include more context in the exception the source
code and the plugin that failed. Attaching this directly to the exception is a
little hacky, but works, and is nice because it keeps the stack trace.
Here's a demo of the decaffeinate repl with this change and a change in
decaffeinate to take advantage of this change: …
> fix: include more information on intermediate parse errors

- src/plugins/functions.arrow.js
- test/form/functions.arrow/skips-bound-generator-functions/_expected/main.js
- test/form/functions.arrow/skips-bound-generator-functions/_expected/metadata.json
- test/form/functions.arrow/skips-bound-generator-functions/main.js
Progress toward https://github.com/decaffeinate/decaffeinate/issues/516
There's no arrow function syntax for generator functions, so we need to keep
them as-is.
> fix: don't transform manually-bound generator functions into arrow functions

- src/utils/needsParens.js
- test/form/functions.arrow/needs-parens-in-or-expression/_expected/main.js
- test/form/functions.arrow/needs-parens-in-or-expression/_expected/metadata.json
- test/form/functions.arrow/needs-parens-in-or-expression/main.js
Fixes https://github.com/decaffeinate/decaffeinate/issues/500
Looks like `||` isn't a BinaryExpression, it's a LogicalExpression, so we need
to check for that as well.
> fix: wrap arrow functions in parens when used in an || expression

- src/esnext.js
Fixes #104
This makes it so callers can actually pass in the list of plugins as an option,
potentially with some entries filtered.
> fix: expose allPlugins as an export

- package.json
- src/plugins/functions.arrow.js
- src/plugins/modules.commonjs.js
- src/plugins/objects.destructuring.js
- src/plugins/strings.template.js
- src/utils/escape.js
Progress toward https://github.com/decaffeinate/decaffeinate/issues/587
This was just a find-and-replace. Note that technically `insertRight` is
equivalent to `prependRight`, but `appendRight` is generally more well-behaved
(it inserts code in order), so it seems nice to switch to that.
> fix: update magic-string dependency and update usage to avoid warnings

- package.json
- src/utils/mostRestrictiveKindForDeclaration.js
- test/form/declarations.block-scope/var-loop-used-across-iterations/_expected/main.js
- test/form/declarations.block-scope/var-loop-used-across-iterations/_expected/metadata.json
- test/form/declarations.block-scope/var-loop-used-across-iterations/_expected/warnings.json
- test/form/declarations.block-scope/var-loop-used-across-iterations/main.js
- test/form/declarations.block-scope/var-loop-with-closure-reference/_expected/main.js
- test/form/declarations.block-scope/var-loop-with-closure-reference/_expected/metadata.json
- test/form/declarations.block-scope/var-loop-with-closure-reference/_expected/warnings.json
- test/form/declarations.block-scope/var-loop-with-closure-reference/main.js
Fixes https://github.com/decaffeinate/decaffeinate/issues/624
Loops make variables tricky because `let` and `const` declarations get a new
variable instance for each loop iteration. This introduces two important
semantic differences:
* Closures referencing `var` variables reference the same variable across all
iterations, whereas for `let`/`const` variables they reference the variable
from the current iteration.
* `var` declarations without an initializer will have the value from the
previous iteration. `let` declarations without an initializer will start as
`undefined`.
To address these cases, I made the `bindingCouldBeBlockScope` function more
conservative. When a variable declaration is within a loop (that exists in the
same function scope as the declaration), we keep `var` if any …
> fix: keep `var` declarations in loops in some unsafe-to-convert cases

- src/plugins/functions.arrow.js
- test/form/functions.arrow/skips-bound-functions-within-new/_expected/main.js
- test/form/functions.arrow/skips-bound-functions-within-new/_expected/metadata.json
- test/form/functions.arrow/skips-bound-functions-within-new/main.js
- test/form/functions.arrow/skips-functions-within-new/_expected/main.js
- test/form/functions.arrow/skips-functions-within-new/_expected/metadata.json
- test/form/functions.arrow/skips-functions-within-new/main.js
Progress toward https://github.com/decaffeinate/decaffeinate/issues/846
It's not allowed to call `new` on an arrow function, so if we can easily
determine that the function is in a `new` expression, skip it. Generally, this
property makes it impossible to determine for sure if it's safe to convert any
function to an arrow function, but this case seems obscure enough that it
shouldn't stop us from converting to arrow functions in normal-looking cases.
> fix: don't convert `new` expressions to arrow functions

- src/plugins/functions.arrow.js
- test/form/functions.arrow/nested-arrow-within-non-arrow/_expected/main.js
- test/form/functions.arrow/nested-arrow-within-non-arrow/_expected/metadata.json
- test/form/functions.arrow/nested-arrow-within-non-arrow/main.js
Fixes https://github.com/decaffeinate/decaffeinate/issues/788
Previously, we stopped searching for `this` in any function, but in some cases,
the only `this` usage is within an arrow function, so we instead should only
stop on the two specific non-arrow-function node types.
> fix: traverse into arrow functions when searching for `this` usages

- src/plugins/modules.commonjs.js
- test/form/modules.commonjs/export-default-class/_expected/main.js
- test/form/modules.commonjs/export-default-class/_expected/metadata.json
- test/form/modules.commonjs/export-default-class/main.js
Fixes https://github.com/decaffeinate/decaffeinate/issues/969
Previously the overwrite logic would incorrectly destroy the open-paren.
> fix: handle a default export on an expression wrapped in parens

- src/esnext.js
- src/plugins/modules.commonjs.js
- src/utils/getFirstUnsafeLocation.js
- test/form/modules.commonjs/converts-require-after-safe-call/_expected/main.js
- test/form/modules.commonjs/converts-require-after-safe-call/_expected/metadata.json
- test/form/modules.commonjs/converts-require-after-safe-call/_expected/warnings.json
- test/form/modules.commonjs/converts-require-after-safe-call/config.json
- test/form/modules.commonjs/converts-require-after-safe-call/main.js
- test/form/modules.commonjs/skips-require-after-function-call/_expected/main.js
- test/form/modules.commonjs/skips-require-after-function-call/_expected/metadata.json
- test/form/modules.commonjs/skips-require-after-function-call/_expected/warnings.json
- test/form/modules.commonjs/skips-require-after-function-call/config.json
- test/form/modules.commonjs/skips-require-after-function-call/main.js
- test/form/modules.commonjs/skips-require-after-increment/_expected/main.js
- test/form/modules.commonjs/skips-require-after-increment/_expected/metadata.json
- test/form/modules.commonjs/skips-require-after-increment/_expected/warnings.json
- test/form/modules.commonjs/skips-require-after-increment/main.js
- test/form/modules.commonjs/skips-require-after-return/_expected/main.js
- test/form/modules.commonjs/skips-require-after-return/_expected/metadata.json
- test/form/modules.commonjs/skips-require-after-return/_expected/warnings.json
- test/form/modules.commonjs/skips-require-after-return/main.js
- test/form/modules.commonjs/skips-require-after-side-effect/_expected/main.js
- test/form/modules.commonjs/skips-require-after-side-effect/_expected/metadata.json
- test/form/modules.commonjs/skips-require-after-side-effect/_expected/warnings.json
- test/form/modules.commonjs/skips-require-after-side-effect/main.js
- test/form/modules.commonjs/skips-require-after-throw/_expected/main.js
- test/form/modules.commonjs/skips-require-after-throw/_expected/metadata.json
- test/form/modules.commonjs/skips-require-after-throw/_expected/warnings.json
- test/form/modules.commonjs/skips-require-after-throw/main.js
Fixes https://github.com/decaffeinate/decaffeinate/issues/982
As soon as we see any statement that could modify `window` (or another global)
in any way, we need to stop converting `require` to `import`, since otherwise we
might introduce bugs due to execution reordering.
> fix: don't convert requires to imports after side effects

- src/plugins/modules.commonjs.js
- test/form/modules.commonjs/converts-complex-forced-default-export/_expected/main.js
- test/form/modules.commonjs/converts-complex-forced-default-export/_expected/metadata.json
- test/form/modules.commonjs/converts-complex-forced-default-export/config.json
- test/form/modules.commonjs/converts-complex-forced-default-export/main.js
- test/form/modules.commonjs/converts-simple-forced-default-export/_expected/main.js
- test/form/modules.commonjs/converts-simple-forced-default-export/_expected/metadata.json
- test/form/modules.commonjs/converts-simple-forced-default-export/config.json
- test/form/modules.commonjs/converts-simple-forced-default-export/main.js
This is useful for code that does complex modifications to `module.exports` and
where we still want to use JS modules. Rather than changing things to exports
line-by-line, we declare an empty exports object at the top, then do the normal
modifications, then `export default` it at the bottom.
> feat: add an option to force a single default export

- src/plugins/modules.commonjs.js
- test/form/modules.commonjs/allows-multiple-named-exports-with-conflicts/_expected/main.js
- test/form/modules.commonjs/allows-multiple-named-exports-with-conflicts/_expected/metadata.json
- test/form/modules.commonjs/allows-multiple-named-exports-with-conflicts/config.json
- test/form/modules.commonjs/allows-multiple-named-exports-with-conflicts/main.js
Fixes https://github.com/decaffeinate/decaffeinate/issues/1012
As in decaffeinate, it's easy to accidentally overwrite code when using
magic-string, so we use appendLeft everywhere and always patch code in order,
which fixes a particular bug involving named exports.
> fix: use appendLeft to avoid magic-string conflicts in modules.commonjs

- index.d.ts
- package.json
I left off the `Plugin.visitor` method since it had a complex type that isn't
necessary for any decaffeinate usages, but it would be needed for any
externally-specified plugins.
> fix: add basic TypeScript types

- index.d.ts
- package.json
We shouldn't use `declare module` for library definitions like this (even though
it usually works).
> fix: clean up typescript definitions, update magic-string

- src/utils/mostRestrictiveKindForDeclaration.js
- test/form/declarations.block-scope/var-in-switch/_expected/main.js
- test/form/declarations.block-scope/var-in-switch/_expected/metadata.json
- test/form/declarations.block-scope/var-in-switch/_expected/warnings.json
- test/form/declarations.block-scope/var-in-switch/config.json
- test/form/declarations.block-scope/var-in-switch/main.js
Fixes https://github.com/decaffeinate/decaffeinate/issues/1171
Potentially add-variable-declarations and esnext could be smarter in this case,
e.g. by declaring the variable outside the switch or even creating a block
scope, but the easy thing is to just keep the declaration as `var`. Since `var`
doesn't have a temporal dead zone, a declaration in any switch case will work
for all switch cases.
> fix: don't convert `var` to `let` or `const` in a switch case

- test/form/declarations.block-scope/var-with-own-binding-in-initializer/_expected/ast.json
- test/form/declarations.block-scope/var-with-own-binding-in-initializer/_expected/warnings.json
It seems `expression` was removed from `ArrowFunctionExpression`.
> test(fixtures): update with new AST format

- package.json
We can't use `yarn publish` from travis since it's interactive.
Probably this could be cleaner with a newer semantic-release, but this should at
least get publish working again.
> chore: fix publish by switching to `npm publish`

- index.d.ts
The DefinitelyTyped typings are for babel-traverse, and that's what we expose as
a package dependency, so we need to just use those for now.
> fix: use babel-traverse, not @babel/traverse in typescript typings

- package.json
- rollup.config.js
- yarn.lock
Also removes the unused import flagged by eslint.
> chore(lint): lint `rollup.config.js` and update eslint

- .circleci/config.yml
- package.json
BREAKING CHANGE: We no longer care about node v6 since it is EOL.
> test(ci): test on node v12 instead of node v6

- packages/resugar-codemod-functions-arrow/src/index.ts
- packages/resugar-codemod-functions-arrow/test/__fixtures__/processes-functions-as-argument-to-new-expression.input.js
- packages/resugar-codemod-functions-arrow/test/__fixtures__/processes-functions-as-argument-to-new-expression.output.js
Refs https://github.com/decaffeinate/decaffeinate/issues/1385.
> fix(codemod-functions-arrow): transform function arguments to `new` expressions

- packages/resugar-codemod-modules-commonjs/package.json
- packages/resugar-codemod-modules-commonjs/src/index.ts
- packages/resugar-codemod-modules-commonjs/test/test.ts
- packages/resugar-helper-comments/package.json
- packages/resugar-helper-comments/src/index.ts
`@babel/traverse` has built-in `NodePath` manipulations like `insertBefore` and `replaceWith`, but these operations do not automatically discover new declarations in the inserted AST nodes. This change manually notifies the scope of new paths to find declarations in.
This prevents situations where a new variable declaration is added but not included in the scope, and a subsequent plugin goes looking for the scope binding associated with the new variable declaration and fails because the scope is out of sync.
> fix: sync scope by registering new declarations

- packages/resugar-codemod-modules-commonjs/src/index.ts
- packages/resugar-codemod-modules-commonjs/test/__fixtures__/adds-a-name-to-exported-anonymous-functions.output.js
- packages/resugar-codemod-modules-commonjs/test/__fixtures__/converts-complex-forced-default-export.output.js
- packages/resugar-codemod-modules-commonjs/test/__fixtures__/does-not-shadow-globals.output.js
- packages/resugar-codemod-modules-commonjs/test/__fixtures__/export-named-global.output.js
- packages/resugar-codemod-modules-commonjs/test/__fixtures__/exports-non-function-values-as-export-let.output.js
- packages/resugar-codemod-modules-commonjs/test/__fixtures__/ignores-a-missing-semi-colon-when-changing-an-export-from-an-assignment-to-export-function.output.js
- packages/resugar-codemod-modules-commonjs/test/__fixtures__/parenthesized-named-export.output.js
- packages/resugar-codemod-modules-commonjs/test/__fixtures__/removes-the-semi-colon-when-changing-an-export-from-an-assignment-to-export-function.output.js
- packages/resugar-codemod-modules-commonjs/test/__fixtures__/rewrites-exports-within-unwrapped-iife.output.js
- packages/resugar-codemod-modules-commonjs/test/__fixtures__/toplevel-this-function-export.output.js
- packages/resugar-codemod-modules-commonjs/test/__fixtures__/works-with-object-destructuring-for-named-exports.output.js
- packages/resugar-codemod-modules-commonjs/test/test.ts
`@babel/traverse` has `Scope#generateUid` which generates a unique ID based on a given name. What I'd like for that method to do is to always use that name if possible, but to generate names based on it if not. That is not how it works, unfortunately, so I wrote my own based on it.
The upshot is that what was previously this:
```js
let _PI = 3.14;
export { _PI as PI };
```
is now this:
```js
export let PI = 3.14;
```
Much nicer.
> fix: allow export declarations to be idiomatic
